### ISSUE TITLE
Add Flameshot to winget package manager

### ISSUE THREAD

**Issue by whnr** [flameshot-org/flameshot#1225]
Hi!

Context: I recently switched to Windows 👎 from my beloved Arch on my work laptop. Windows has a package manager now [winget](https://github.com/microsoft/winget-cli)!

It would be awesome to add Flameshot to that. It seems to be a simple yaml file added to https://github.com/microsoft/winget-pkgs.

**Comment by whnr** [comment]
Here is a sample yaml that works (you'll only get asked about trusting the unknown publisher). You can try it with something like `winget install -m 0.8.4.0.yaml`

```yaml
Id: flameshotorg.flameshot
Publisher: flameshot-org
Name: flameshot
Version: 0.8.4.0
License: GNU General Public License v3.0
InstallerType: MSI
LicenseUrl: https://github.com/flameshot-org/flameshot/blob/master/LICENSE
AppMoniker: 
Tags: snipping,screenshot
Description: Powerful yet simple to use screenshot software with annotation tools and imgur upload
Homepage: https://flameshot.org/
Installers:
  - Arch: x86
    InstallerType: MSI
    Url: https://github.com/flameshot-org/flameshot/releases/download/v0.8.4/Flameshot-0.8.4-win32.msi
    Sha256: 0D23E5A5C029B1D195410B84BFEFD551784741657F60C47142CBF0640419CEDF
    Silent: /passive
  - Arch: x64
    InstallerType: MSI
    Url: https://github.com/flameshot-org/flameshot/releases/download/v0.8.4/Flameshot-0.8.4-win64.msi
    Sha256: 91CB939D440D8A00ACDBB995177E88ACBBB0609E69C2ABA471883D11A0A3AC67
    Silent: /passive
```
