### ISSUE TITLE
Copy (capture) hotkeys stopped working

### ISSUE THREAD

**Issue by mkbaranovskyi** [flameshot-org/flameshot#1443]
**Flameshot version**
Flameshot v0.9.0
Compiled with Qt 5.15.2

**Describe the bug**
At some point (maybe after an update to 0.9.0 recently) my hotkeys for capturing and copying - `Enter`, `NumpadEnter`, `Ctrl + C` - stopped working. The gui for making screens opens up, I can click buttons and change settings but when I press the usual hotkeys for copying my screenshot to the buffer - nothing happens. I opened the new Shortcuts panel and you can see that none of them is mentioned and even the option itself is absent.
![image](https://user-images.githubusercontent.com/39165507/110618892-d946a180-819f-11eb-99f5-29e8de8da5c8.png)
Though, I can still copy/capture my screenshot using the interface button in the `flameshot gui` window - it's there. 

**To Reproduce**
Just the usual screenshot creation using `flameshot gui`

**Expected behavior**
My screenshot to be saved to the buffer and the `flameshot gui` window to be closed. 

**System Information**
```
System:
  Host: user-comp Kernel: 5.10.19-1-MANJARO x86_64 bits: 64 Desktop: GNOME 3.38.3 
  Distro: Manjaro Linux 
Graphics:
  Device-1: AMD Hawaii XT / Grenada XT [Radeon R9 290X/390X] driver: radeon 
  v: kernel 
  Display: x11 server: X.org 1.20.10 driver: loaded: ati,radeon 
  unloaded: modesetting resolution: <missing: xdpyinfo> 
  OpenGL: renderer: AMD HAWAII (DRM 2.50.0 5.10.19-1-MANJARO LLVM 11.1.0) 
  v: 4.5 Mesa 20.3.4
```

Upd. And also "undo/redo" buttons stopped working and are absent in the list.
