### ISSUE TITLE
Windows move when using command flameshot gui

### ISSUE THREAD

**Issue by RicardoSQueen** [flameshot-org/flameshot#1605]
**Flameshot version**

Flameshot v0.9.0
Compiled with Qt 5.15.2

**Describe the bug**

Everytime `flameshot gui` is called, windows are moved (to the left) as the GUI is opened. After screenshot is taken every window goes back to its previous location:
![image](https://user-images.githubusercontent.com/64474885/116952756-d200b900-ac61-11eb-8db1-a91035697fa8.png)
This is a screenshot from a screen, where the terminal was maximized and the browser was on my 2nd monitor (to the right) before the command. After the command the window was back to 'normal' maximized state.
Actually, to be more precise, it doesn't seem that it's just the windows that are moving: Looking closely, the bottom panel on my KDE environment also moves to the left.

**To Reproduce**

run `flameshot gui` and observe behaviour

**Expected behavior**

Windows stay in the same place as they were.

**System Information**
Linux r**** 5.11.16-2-MANJARO #1 SMP PREEMPT Thu Apr 22 09:53:11 UTC 2021 x86_64 GNU/Linux

```
System:

  Host: ***** Kernel: 5.11.16-2-MANJARO x86_64 bits: 64 
  Desktop: KDE Plasma 5.21.4 Distro: Manjaro Linux 
Graphics:
  Device-1: AMD Picasso driver: amdgpu v: kernel 
  Device-2: Syntek Integrated Camera type: USB driver: uvcvideo 
  Display: x11 server: X.Org 1.20.11 driver: loaded: amdgpu,ati 
  unloaded: modesetting resolution: 1: 1920x1080~60Hz 2: 1920x1080~75Hz 
  OpenGL: renderer: AMD Radeon Vega 10 Graphics (RAVEN DRM 3.40.0 
  5.11.16-2-MANJARO LLVM 11.1.0) 
  v: 4.6 Mesa 21.0.3 

```
