### ISSUE TITLE
Gnome40/Wayland unable to capture screen with latest build (e4e7c90)

### ISSUE THREAD

**Issue by XMoon** [flameshot-org/flameshot#2041]
**Flameshot version**

Flameshot v0.10.1 (e4e7c901)
Compiled with Qt 5.15.2

**Describe the bug**

unable to capture screen when using build e4e7c901 in Gnome40 / Wayland.

Not found any error log in console, only a notify in gnome view show `flameshot info : unable to capture screen`

but build 5021457 is ok.

**To Reproduce**

using build e4e7c901 in Gnome 40 /wayland & run flameshot gui.

**System Information**

```
System:
  Host: LLAP-Lyoko Kernel: 5.14.16-arch1-1 x86_64 bits: 64 Desktop: GNOME 40.5
  Distro: Arch Linux
Graphics:
  Device-1: AMD Renoir driver: amdgpu v: kernel
  Device-2: IMC Networks Integrated Camera type: USB driver: uvcvideo
  Display: wayland server: X.Org 1.21.1.2 driver: loaded: amdgpu
  unloaded: modesetting resolution: 1: 1920x1080~60Hz 2: 1920x1080~60Hz
  3: 2560x1600~60Hz
  OpenGL: renderer: AMD RENOIR (DRM 3.42.0 5.14.16-arch1-1 LLVM 12.0.1)
  v: 4.6 Mesa 21.2.4
```
