### ISSUE TITLE
only top left part is ready for operation in wayland with multiple monitors

### ISSUE THREAD

**Issue by lilydjwg** [flameshot-org/flameshot#2086]
**Flameshot version**
Flameshot v0.10.1
Compiled with Qt 5.15.2

**Describe the bug**
I have two monitors arranged like this (the cyan and green rectangles):

![图片](https://user-images.githubusercontent.com/440661/142227373-09e43b06-6bcb-4651-806d-079c301aadf5.png)

When I run `flameshot gui` on the green monitor, flameshot shows an image covering that monitor, but only top left part (the area in the red rectangle).

**To Reproduce**
1. run `XDG_CURRENT_DESKTOP=sway flameshot &`
2. run `flameshot gui`
3. see

**Expected behavior**
If flameshot can't cover all monitors like on X11, I hope it captures and covers only the monitor I run it so I can see and edit the area I intend to capture.

**System Information**
Arch Linux current. Wayfire git. wlroots git.

**Comment by mmahmoudian** [comment]
@lilydjwg What are the resolution of those two monitors? For example you can use `inxi --graphics`

**Comment by lilydjwg** [comment]
The left one is 1920x1080 scale 1.5. The right one is 3840x2160 scale 2. The left one is shifted down several hundred pixels to match the position in reality.

`inxi` doesn't work well on Wayland.

**Comment by mmahmoudian** [comment]
Can you try having the scale of your left monitor to 100% or 200% and try again. This issue might be the result of fractional scaling.

**Comment by lilydjwg** [comment]
Tried set left to 1, still only top left part is shown and editable: that's about half of blank and half of top part of my left monitor's display.

**Comment by mfzha** [comment]
+1 to this issue. For reference @mmahmoudian here is what `inxi --graphics` looks like (note I'm still running on X11, KDE Plasma).
```
Graphics:
  Device-1: AMD Ellesmere [Radeon RX
  470/480/570/570X/580/580X/590]
  driver: amdgpu v: kernel
  Device-2: SunplusIT USB 2.0 Camera type: USB
  driver: snd-usb-audio,uvcvideo
  Display: x11 server: X.Org 1.21.1.3 driver: loaded: amdgpu,ati
  unloaded: fbdev,modesetting,vesa resolution: 1: 3440x1440
  2: 1080x1920
  OpenGL: renderer: AMD Radeon RX 580 Series (POLARIS10 DRM
  3.44.0 5.16.0-1-default LLVM 13.0.0)
  v: 4.6 Mesa 21.3.3
```

Tested with various types of scaling, and that doesn't seem to be fixing it.
