### ISSUE TITLE
Arch package out of date

### ISSUE THREAD

**Issue by Metacinnabar** [flameshot-org/flameshot#2095]
### Flameshot Version

v0.10.1-1

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

EndeavourOS 1.4

### Description

The official [Arch package](https://archlinux.org/packages/community/x86_64/flameshot/) is version `v0.10.1-1` yet the latest version is `v0.10.2`.

### Steps to reproduce

1. `sudo pacman -S flameshot`.
2. Take a screenshot and get notified of being out of date.

### System Information

```
System:
  Host: headpat-el Kernel: 5.13.12-arch1-1 x86_64 bits: 64
  Desktop: Xfce 4.16.0 Distro: EndeavourOS
Graphics:
  Device-1: Intel GeminiLake [UHD Graphics 600] driver: i915 v: kernel
  Device-2: Acer SunplusIT Integrated Camera type: USB driver: uvcvideo
  Device-3: Acer Integrated 5M Camera type: USB driver: uvcvideo
  Display: x11 server: X.org 1.21.1.1 driver: loaded: intel
  unloaded: fbdev,modesetting,vesa resolution: <missing: xdpyinfo>
  OpenGL: renderer: Mesa Intel UHD Graphics 600 (GLK 2) v: 4.6 Mesa 21.2.5
 ```
 ```
Linux headpat-el 5.13.12-arch1-1 #1 SMP PREEMPT Wed, 18 Aug 2021 20:49:03 +0000 x86_64 GNU/Linux
 ```
