### ISSUE TITLE
Bump homebrew cask on every release

### ISSUE THREAD

**Issue by nitrocode** [flameshot-org/flameshot#2096]
### Feature Description

This github action should do the trick

https://github.com/marketplace/actions/bump-homebrew-formula

```yaml
on:
  push:
    tags: 'v*'

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          # A PR will be sent to github.com/Homebrew/homebrew-core to update this formula:
          formula-name: flameshot
          homebrew-tap: Homebrew/homebrew-cask
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
```

This will prevent maintainer contributions like this https://github.com/Homebrew/homebrew-cask/pull/114630 and will speed up the latest version's availability on homebrew
