### ISSUE TITLE
Can't disable systray. It always there if I open flameshot again.

### ISSUE THREAD

**Issue by rizzini** [flameshot-org/flameshot#2116]
### Flameshot Version

Flameshot v0.10.1 (48c9d472)
Compiled with Qt 5.15.2

### Installation Type

User repository (AUR)

### Operating System type and version

ArchLinux 64bits

### Description

Even if I disable systray, it appears again when flameshot is restarted.

### Steps to reproduce

1. run flameshot
2. Disable systray
3. Close flameshot
4. Open it again and the systray will be there anyway.

### Screenshots or screen recordings

https://gofile.io/d/06zXpZ

### System Information

```
[lucas@archlinux ~]$ inxi --width 80 --system --graphics
System:
  Host: archlinux Kernel: 5.15.3-220-tkg-pds x86_64 bits: 64
  Desktop: KDE Plasma 5.23.3 Distro: Arch Linux
Graphics:
  Device-1: Intel 4th Generation Core Processor Family Integrated Graphics
  driver: i915 v: kernel
  Device-2: NVIDIA G92 [GeForce 9800 GT] driver: nvidia v: 340.108
  Device-3: GEMBIRD USB2.0 PC CAMERA type: USB driver: snd-usb-audio,uvcvideo
  Display: x11 server: X.Org 1.21.1.1 driver: loaded: intel
  resolution: 1920x1080
  OpenGL: renderer: Mesa DRI Intel HD Graphics 4400 (HSW GT2)
  v: 4.5 Mesa 21.2.5
```
