### ISSUE TITLE
Flameshot Crash

### ISSUE THREAD

**Issue by madhur** [flameshot-org/flameshot#2606]
### Flameshot Version

Flameshot v11.0.0 ()
Compiled with Qt 5.15.3

### Installation Type

Snap from Snapcraft

### Operating System type and version

Cent OS 8.5

### Description

When I start flameshot, it starts correctly and tray icon appears on tray list. When I click and draw a rectangle, it works fine till this point. After I click save button, it crashes with below stack trace.

```
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
flameshot: error: Locales on your system are not properly configured. Falling back to defaults
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
[1]    569797 abort (core dumped)  flameshot
```

### Steps to reproduce

When I start flameshot, it starts correctly and tray icon appears on tray list. When I click and draw a rectangle, it works fine till this point. After I click save button, it crashes with below stack trace.

### System Information

```
System:
  Host: localhost.localdomain Kernel: 5.16.2-1.el8.elrepo.x86_64 arch: x86_64
    bits: 64 Desktop: i3 v: 4.20.1-2-gacde5122
    Distro: CentOS Linux release 8.5.2111
Graphics:
  Device-1: NVIDIA GA106 [GeForce RTX 3060 Lite Hash Rate] driver: nvidia
    v: 510.60.02
  Display: x11 server: X.Org v: 1.20.11 driver: X: loaded: nvidia
    gpu: nvidia resolution: 3840x2160~60Hz
  OpenGL: renderer: NVIDIA GeForce RTX 3060/PCIe/SSE2
    v: 4.6.0 NVIDIA 510.60.02
```

```
Monitors: 1
 0: +DP-2 3840/698x2160/393+0+0  DP-2

```
```
Screen 0: minimum 8 x 8, current 3840 x 2160, maximum 32767 x 32767
DP-2 connected 3840x2160+0+0 (normal left inverted right x axis y axis) 698mm x 393mm
   3840x2160     60.00*+  59.94    50.00    29.97    25.00    23.98  
   2560x1440     59.95  
   1920x1080     60.00    59.94    50.00  
   1680x1050     59.95  
   1440x900      59.89  
   1280x1024     60.02  
   1280x960      60.00  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1024x768      60.00  
   800x600       60.32    56.25  
   720x576       50.00  
   720x480       59.94  
   640x480       59.94    59.93  
```

```
  *-display                 
       description: VGA compatible controller
       product: GA106 [GeForce RTX 3060 Lite Hash Rate]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:05:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:97 memory:fb000000-fbffffff memory:d0000000-dfffffff memory:e0000000-e1ffffff ioport:e000(size=128) memory:fc000000-fc07ffff
  *-graphics
       product: simple
       physical id: 1
       logical name: /dev/fb0
       capabilities: fb
       configuration: depth=32 resolution=1024,768
```

```
Linux localhost.localdomain 5.16.2-1.el8.elrepo.x86_64 #1 SMP PREEMPT Tue Jan 18 15:26:58 EST 2022 x86_64 x86_64 x86_64 GNU/Linux

```
