### ISSUE TITLE
Flameshot not working on Plasma Wayland

### ISSUE THREAD

**Issue by DemonicSavage** [flameshot-org/flameshot#2660]
### Flameshot Version

```
Flameshot v11.0.0 (-)
Compiled with Qt 5.15.3
```

### Installation Type

Flatpak from Flathub

### Operating System type and version

Arch Linux

### Description

When I open Flameshot and click on "Take Screenshot" in the system tray icon, nothing happens.
"Open Launcher" opens the launcher, but "Take new screenshot" does nothing.

### Steps to reproduce

1. Run Flameshot
2. Click on "Take Screenshot" on system tray icon

### System Information

```
System:
  Host: Belphegor Kernel: 5.18.3-zen1-1-zen arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.24.5 Distro: Arch Linux
Graphics:
  Device-1: AMD Navi 23 [Radeon RX 6600/6600 XT/6600M] driver: amdgpu
    v: kernel
  Device-2: Generalplus GENERAL WEBCAM type: USB
    driver: snd-usb-audio,uvcvideo
  Display: wayland server: X.org v: 1.21.1.3 with: Xwayland v: 22.1.2
    compositor: kwin_wayland driver: X: loaded: amdgpu unloaded: modesetting
    gpu: amdgpu resolution: 1: 1920x1080 2: 1920x1080
  OpenGL: renderer: AMD Radeon RX 6600 XT (dimgrey_cavefish LLVM 13.0.1 DRM
    3.46 5.18.3-zen1-1-zen)
    v: 4.6 Mesa 22.1.1
```

Both `xdg-desktop-portal` and `xdg-desktop-portal-kde` are installed.
