### ISSUE TITLE
flameshot gui delayed compared to tray icon click

### ISSUE THREAD

**Issue by JokelaR** [flameshot-org/flameshot#2713]
### Flameshot Version

Flameshot v12.0.0 (b4737f8a)
Compiled with Qt 5.15.4

### Installation Type

User repository (AUR)

### Operating System type and version

linux: 5.18.5-1-MANJARO (KDE)

### Description

Starting a gui screenshot is noticably slower (up to a second of delay) when invoked through `flameshot gui` or a comparable KDE keyboard shortcut compared to clicking on the tray icon. 

### Steps to reproduce

1. Have flameshot running
2. Click on tray icon
3. Observe near instant start of gui
4. Run `flameshot gui` in a terminal
5. Observe a delayed start of the gui 

### System Information

```
System:
  Host: nitronp51551 Kernel: 5.18.5-1-MANJARO arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.24.5 Distro: Manjaro Linux
Graphics:
  Device-1: Intel UHD Graphics 620 driver: i915 v: kernel
  Device-2: NVIDIA GP107M [GeForce GTX 1050 Mobile] driver: N/A
  Display: x11 server: X.Org v: 21.1.3 with: Xwayland v: 22.1.2 driver: X:
    loaded: modesetting gpu: i915 resolution: 1: 1920x1080~60Hz
    2: 1920x1080~60Hz
  OpenGL: renderer: Mesa Intel UHD Graphics 620 (KBL GT2) v: 4.6 Mesa 22.1.1
```
Display configuration: Internal and external display side by side
![image](https://user-images.githubusercontent.com/4138317/175341882-49aa3c15-d689-4269-8c6c-13c3144baf45.png)

**Comment by mmahmoudian** [comment]
I am on Manjaro KDE and cannot reproduce this. when daemon is running, both left-click on tray icon and `flameshot gui` open in the same rate.

The only major differences I see between my setup and yours are:
1. I have 3 monitors
2. I use proprietary Nvidia driver and you use Mesa

```console
❯  inxi --width 80 --system --graphics
System:
  Host: Chrstphr Kernel: 5.15.50-1-MANJARO arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.24.5 Distro: Manjaro Linux
Graphics:
  Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics
    driver: i915 v: kernel
  Device-2: NVIDIA GP106 [GeForce GTX 1060 6GB] driver: nvidia v: 515.57
  Display: x11 server: X.Org v: 21.1.3 driver: X: loaded: modesetting,nvidia
    gpu: i915 resolution: 1: 1080x1920~60Hz 2: 1080x1920~60Hz 3: 1920x1080~60Hz
  OpenGL: renderer: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
    v: 4.6.0 NVIDIA 515.57
```

![image](https://user-images.githubusercontent.com/390889/178062578-5d14f74c-4260-4469-84e9-0cad68cc215e.png)


Do you see the same lag when you unplug your external monitor?

**Comment by JokelaR** [comment]
> Do you see the same lag when you unplug your external monitor?

I can confirm that the delay is still there with no external monitors plugged in.

**Comment by pintassilgo** [comment]
I can reproduce this. A good way to test is having this page focused before you take a screenshot, with scrollbar all to the top. Then you click (or press) to take screenshot and immediately press `End` keyboard key to scroll to the bottom of the page.

In a perfect world of 0 delay, Flameshot should be fast enough to take a screenshot of the top of the page, before the page scrolling caused by `End` key.

My results:
- If I press `End` immediately after clicking tray icon, Flameshot is unable to take a screenshot from the top of the page.
- If I press `End` very quickly but not *immediately*, Flameshot is able to take a screenshot from the top of the page **only if** done by clicking tray icon. Other ways like keyboard shortcut (usually PrintScreen), `flameshot gui` or even `Take screenshot` from tray icon context menu (right-click) are noticeably slower in this test.


So Flameshot is never "0 delay", but clicking tray icon is clearly faster than any other method.

How to make keyboard shortcut to be as fast as clicking tray icon?

```
System:
  Host: ---- Kernel: 5.18.11-1-default arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.25.3 Distro: openSUSE Tumbleweed 20220725
Graphics:
  Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
    driver: amdgpu v: kernel
  Display: wayland server: X.org v: 1.21.1.4 with: Xwayland v: 22.1.3
    compositor: kwin_wayland driver: X: loaded: modesetting unloaded: fbdev,vesa
    gpu: amdgpu resolution: 2560x1080
  OpenGL: renderer: AMD Radeon RX 570 Series (polaris10 LLVM 14.0.6 DRM 3.46
  5.18.11-1-default)
    v: 4.6 Mesa 22.1.3
```
