### ISSUE TITLE
Flameshot not working on Fedora36 Workstation (Wayland)

### ISSUE THREAD

**Issue by Gabriel-Espinoza** [flameshot-org/flameshot#2745]
### Flameshot Version

Flameshot v12.0.0 (-)
Compiled with Qt 5.15.3
linux: 5.18.6-200.fc36.x86_64
fedora: 36

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Fedora 36 Workstation, Wayland

### Description

Flameshot does not open the gui right away, instead it opens a gnome snapshot utility with a full screen snapshot. When pressing share button in the utility it opens flameshot gui.

### Steps to reproduce

1. Install fedora36 workstation
2. Log in to your desktop using Wayland
3. Install flameshot using snap, flatpak or dnf (fedora repositories)
4. run flameshut by `flameshot gui`
5. The Gnome snapshot tool will take a full screen screenshot
6. If you press share, it shows flameshot's GUI

### Screenshots or screen recordings

when running `flameshot gui`
![image](https://user-images.githubusercontent.com/2473212/176905025-3274717a-4c2b-45d4-b56e-78ce1ac0c854.png)

when pressing **share** button
![image](https://user-images.githubusercontent.com/2473212/176905070-60f024bd-acfa-4db6-b2d4-e7fc66684c39.png)

Terminal output after pressing escape while in gnome snapshot
```
[gabrielespinoza@PC-Gabo ~]$ flameshot gui
flameshot: error: Unable to capture screen
flameshot: error: Unable to capture screen
qt.svg: Invalid path data; path truncated.
qt.svg: Invalid path data; path truncated.
flameshot: info: Screenshot aborted.
```

### System Information

```
System:
  Host: PC-Gabo Kernel: 5.18.6-200.fc36.x86_64 arch: x86_64 bits: 64
    Desktop: GNOME v: 42.2 Distro: Fedora release 36 (Thirty Six)
Graphics:
  Device-1: AMD Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M]
    driver: amdgpu v: kernel
  Device-2: Huawei UVC Camera type: USB driver: snd-usb-audio,uvcvideo
  Display: wayland server: X.Org v: 1.22.1.2 with: Xwayland v: 22.1.2
    compositor: gnome-shell driver: X: loaded: amdgpu
    unloaded: fbdev,modesetting,radeon,vesa gpu: amdgpu resolution:
    1: 2560x1440~60Hz 2: 1080x1920~60Hz
  OpenGL: renderer: AMD Radeon RX 6700 XT (navy_flounder LLVM 14.0.0 DRM
    3.46 5.18.6-200.fc36.x86_64)
    v: 4.6 Mesa 22.1.2
```
