### ISSUE TITLE
screenshot teared/corrupted with "flameshot screen" on second monitor

### ISSUE THREAD

**Issue by Teal2CA** [flameshot-org/flameshot#2910]
### Flameshot Version

Flameshot v12.1.0 (-)
Compiled with Qt 5.15.4

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Linux (void linux) 5.18.19_1

### Description

i have an issue with "flameshot screen" where the result screenshot contains tearing/corruption only on my main monitor.
- ```flameshot full``` works perfectly fine, so does ```flameshot gui```
- ```flameshot screen``` on my second monitor works as expected, but not on my main monitor.

### Steps to reproduce

1. run ```flameshot screen -d 2000```
2. quickly move cursor to main monitor

### Screenshots or screen recordings

screenshots taken on main monitor, notice how it glitches through wallpaper and firefox which is on second monitor and how retaking the same screen without changes over and over produces different results
![2022-09-17_11-57](https://user-images.githubusercontent.com/96055193/190394409-ae48b18c-b568-43a8-a64c-6eba285bcc5c.png)
![2022-09-17_11-58](https://user-images.githubusercontent.com/96055193/190394443-1930c429-a6c8-48c0-bf59-a2f2f773c125.png)
![2022-09-17_11-58_3](https://user-images.githubusercontent.com/96055193/190394456-250d2d8c-a509-4cb7-b4ed-eb532a902df0.png)

expected result:
![2022-09-17_12-40](https://user-images.githubusercontent.com/96055193/190396772-b1fa478c-51f9-4c14-b061-00a340c59448.png)

### System Information

uname -a
```
Linux hostname 5.18.19_1 #1 SMP PREEMPT_DYNAMIC Thu Aug 25 14:36:55 UTC 2022 x86_64 GNU/Linux
```
inxi --width 80 --system --graphics
```
System:
  Host: hostname Kernel: 5.18.19_1 arch: x86_64 bits: 64 Desktop: bspwm
    v: 0.9.10 Distro: Void Linux
Graphics:
  Device-1: NVIDIA GP108 [GeForce GT 1030] driver: nvidia v: 515.65.01
  Display: server: X.Org v: 21.1.4 driver: X: loaded: nvidia
    unloaded: fbdev,modesetting,nouveau,vesa gpu: nvidia resolution:
    1: 1920x1080~60Hz 2: 1280x1024~60Hz
  OpenGL: renderer: NVIDIA GeForce GT 1030/PCIe/SSE2
    v: 4.6.0 NVIDIA 515.65.01
```
### monitor configuration:
xrandr --listactivemonitors
```
Monitors: 2
 0: +*DP-0 1920/477x1080/268+1280+0  DP-0
 1: +HDMI-0 1280/300x1024/230+0+0  HDMI-0
```
#### layout (sorry!)
```
#####################################
#            #                      #
#            #                      #
#   HDMI-0   #         DP-0         #
#            #                      #
##############                      #
             ########################
```
wm: bspwm 0.9.10
compositor: picom v9.1
