### ISSUE TITLE
Flameshot can't pin

### ISSUE THREAD

**Issue by cnut1648** [flameshot-org/flameshot#2918]
### Flameshot Version

Flameshot v12.1.0 (-)
Compiled with Qt 5.15.5
linux: 5.19.7-1-MANJARO
manjaro: unknown

### Installation Type

User repository (AUR)

### Operating System type and version

Manjaro 5.19.7-1

### Description

My pin functionality works fine in some app like browser, but does not work in most apps like console, vs code, or file browser.
I have recorded a gif below. The errror is
```
QPainter::begin: Paint device returned engine == 0, type: 2 546  13:57:18 
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setBrush: Painter not active
```

### Steps to reproduce

1. run `flameshot &` on a console
2. select region with gui and click pin button
3. no pinned image shows up

### Screenshots or screen recordings

![Peek 2022-09-24 14-00](https://user-images.githubusercontent.com/37067883/192112288-8866a362-02fb-4593-934b-5b1f04b3ce24.gif)

### System Information

- Manjaro 5.19.7-1 on a laptop
- I recorded the gif in an external monitor 
![image](https://user-images.githubusercontent.com/37067883/192112396-82c8d5b7-f5c9-4b9c-862c-66eee2fa8fc7.png)
but it also doesn't work on my lcoal laptop
- I am using KDE but with i3wm

**Comment by mmahmoudian** [comment]
It is crucial for us to know all the information we asked in the form. Please complete the information. Also you either have a mistake in the version you reported, or in the method of installation.

We cannot investigate without the details we asked for.

**Comment by cnut1648** [comment]
Hi @mmahmoudian can you specific which information I am missing please? 

Based on [this webpage](https://flameshot.org/docs/guide/issue-reporting/) I listed the output of commands below:
Flameshot version
```
Flameshot v12.1.0 (-)
Compiled with Qt 5.15.5
```

system information
```
System:
  Host: chris-aero15xa Kernel: 5.19.7-1-MANJARO arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.25.5 Distro: Manjaro Linux
Graphics:
  Device-1: Intel CoffeeLake-H GT2 [UHD Graphics 630] driver: i915 v: kernel
  Device-2: NVIDIA TU106M [GeForce RTX 2070 Mobile] driver: nvidia
    v: 515.65.01
  Device-3: IMC Networks USB2.0 HD UVC WebCam type: USB driver: uvcvideo
  Display: x11 server: X.Org v: 21.1.4 with: Xwayland v: 22.1.3 driver: X:
    loaded: modesetting,nvidia gpu: i915 resolution: 1: 3840x2160~60Hz
    2: 3840x2160~60Hz
  OpenGL: renderer: NVIDIA GeForce RTX 2070 with Max-Q Design/PCIe/SSE2
    v: 4.6.0 NVIDIA 515.65.01
```
I'm using `x11` 
Monitor(s) information
```
Screen 0: minimum 8 x 8, current 8522 x 2313, maximum 32767 x 32767
eDP-1-1 connected 3840x2160+0+0 (normal left inverted right x axis y axis) 344mm x 194mm
   3840x2160     60.00*+  59.98    59.97  
   3200x1800     59.96    59.94  
   2880x1620     59.96    59.97  
   2560x1600     59.99    59.97  
   2560x1440     59.99    59.99    59.96    59.95  
   2048x1536     60.00  
   1920x1440     60.00  
   1856x1392     60.01  
   1792x1344     60.01  
   2048x1152     59.99    59.98    59.90    59.91  
   1920x1200     59.88    59.95  
   1920x1080     60.01    59.97    59.96    59.93  
   1600x1200     60.00  
   1680x1050     59.95    59.88  
   1400x1050     59.98  
   1600x900      59.99    59.94    59.95    59.82  
   1280x1024     60.02  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1440x810      60.00    59.97  
   1368x768      59.88    59.85  
   1280x800      59.99    59.97    59.81    59.91  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   640x400       59.88    59.98  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
DP-1-1 connected primary 3840x2160+4682+153 (normal left inverted right x axis y axis) 621mm x 341mm
   3840x2160     60.00*+  29.98  
   2560x1600     59.97  
   2560x1440     59.95  
   1920x1080     60.00    60.00    50.00    59.94  
   1920x1080i    60.00    50.00    59.94  
   1680x1050     59.88  
   1280x1024     75.02    60.02  
   1440x900      59.90  
   1280x960      60.00  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1440x576      50.00  
   1024x768      75.03    70.07    60.00  
   1440x480      60.00    59.94  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    72.81    66.67    60.00    59.94  
   720x400       70.08  
```
Graphic cards
```
00:02.0 VGA compatible controller: Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630]
01:00.0 VGA compatible controller: NVIDIA Corporation TU106M [GeForce RTX 2070 Mobile] (rev a1)
```

Operating system information
```
Linux chris-aero15xa 5.19.7-1-MANJARO #1 SMP PREEMPT_DYNAMIC Mon Sep 5 10:16:57 UTC 2022 x86_64 GNU/Linux
```
Thanks!
