### ISSUE TITLE
[Arch Linux KDE] qt.qpa.wayland: Wayland does not support QWindow::requestActivate()

### ISSUE THREAD

**Issue by andreacorinti** [flameshot-org/flameshot#2974]
### Flameshot Version

```
Flameshot v12.1.0 (-)
Compiled with Qt 5.15.5
```

### Installation Type

User repository (AUR)

### Operating System type and version

Arch Linux

### Description

Everything was working fine until today, maybe some updates messed up something

### Steps to reproduce

```
xab@archxab ~ :( $ flameshot gui
flameshot: error: Unable to capture screen
flameshot: error: Unable to capture screen
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
flameshot: info: Screenshot aborted.

```

### System Information

```
System:
  Host: archxab Kernel: 6.0.7-arch1-1 arch: x86_64 bits: 64 Desktop: KDE Plasma
    v: 5.26.3 Distro: Arch Linux
Graphics:
  Device-1: NVIDIA TU117M [GeForce GTX 1650 Mobile / Max-Q] driver: nouveau
    v: kernel
  Device-2: AMD Picasso/Raven 2 [Radeon Vega Series / Radeon Mobile Series]
    driver: amdgpu v: kernel
  Device-3: Azurewave USB2.0 HD UVC WebCam type: USB driver: uvcvideo
  Display: wayland server: X.org v: 1.21.1.4 with: Xwayland v: 22.1.5
    compositor: kwin_wayland driver: X: loaded: amdgpu,modesetting
    dri: radeonsi,nouveau gpu: nouveau,amdgpu resolution: 1920x1080
  API: OpenGL v: 4.6 Mesa 22.2.3 renderer: AMD Radeon Vega 10 Graphics
    (raven LLVM 14.0.6 DRM 3.48 6.0.7-arch1-1)

```

**Comment by CoelacanthusHex** [comment]
Same issue here.
```
Flameshot v12.1.0 (-)
Compiled with Qt 5.15.5
```

From Arch Official Repo.
```
System:
  Host: new-laptop.coelacanthus.internal Kernel: 6.0.7-zen1-1-zen arch: x86_64
    bits: 64 Desktop: KDE Plasma v: 5.26.3 Distro: Arch Linux
Graphics:
  Device-1: NVIDIA GA107BM [GeForce RTX 3050 Mobile] driver: nvidia
    v: 520.56.06
  Device-2: AMD Cezanne [Radeon Vega Series / Radeon Mobile Series]
    driver: amdgpu v: kernel
  Device-3: IMC Networks Integrated Camera type: USB driver: uvcvideo
  Display: wayland server: X.org v: 1.21.1.4 with: Xwayland v: 22.1.5
    compositor: kwin_wayland driver: X: loaded: modesetting unloaded: nvidia
    dri: radeonsi,nouveau gpu: nvidia,amdgpu resolution: 1920x1080
  API: OpenGL v: 4.6 Mesa 22.2.3 renderer: AMD Radeon Graphics (renoir LLVM
    14.0.6 DRM 3.48 6.0.7-zen1-1-zen)
```

**Comment by mmahmoudian** [comment]
can you both confirm that you were using the KDE Wayland before this as well.

**Comment by 5thHarbinger** [comment]
Same here, also with version `v12.1.0 (-)`

I'm on Fedora, not Arch, but also use KDE Wayland

When I start flameshot gui normally I also get `qt.qpa.wayland: Wayland does not support QWindow::requestActivate()` so I don't think opening another issue is needed

Also, it works when launching with the env `QT_QPA_PLATFORM=xcb` as suggested [here](https://github.com/flameshot-org/flameshot/issues/1184#issuecomment-745528488) but then keybinds won't work

**Comment by alxndr13** [comment]
Got the same issue, but without KDE. I'm using sway.

**Comment by dvoytik** [comment]
Same problem on sway. Executing sway according to https://github.com/flameshot-org/flameshot/blob/master/docs/Sway%20and%20wlroots%20support.md

**Comment by koloved** [comment]
I have the same problem, but it kinda works but it always open on second monitor



**inxi --graphics --system --width=80**
System:
Host: green-b660mitxac Kernel: 6.1.6-zen1-1-zen arch: x86_64 bits: 64
Desktop: KDE Plasma v: 5.26.5 Distro: Garuda Linux
Graphics:
Device-1: NVIDIA GA106 [Geforce RTX 3050] driver: nvidia v: 525.78.01
Device-2: ANYKA V380 FHD Camera type: USB driver: snd-usb-audio,uvcvideo
Display: wayland server: X.org v: 1.21.1.6 with: Xwayland v: 22.1.7
compositor: kwin_wayland driver: N/A resolution: 1: 1920x1080 2: 1920x1080
API: OpenGL v: 4.6.0 NVIDIA 525.78.01 renderer: NVIDIA GeForce RTX
3050/PCIe/SSE2

 **flameshot gui**
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
flameshot: info: Screenshot aborted.

**Comment by DragoonAethis** [comment]
Fixed it on my system, but how it got into the broken state in the first place, I have no idea.

In your `~/.config/kwinrc`, go to section `[Plugins]`, find `screenshotEnabled=false` and set it to `true`. This is apparently an internal plugin that can be disabled in KCM Workspace Behavior -> Desktop Effects (if you click on the Filter icon and uncheck Exclude Internal Effects).

**Comment by adamant-pwn** [comment]
I recently started having the same problem on Hyprland. Worked fine before...

**Comment by italovieira** [comment]
I'm having the same problem:

```
Flameshot v12.1.0 (-)
Compiled with Qt 5.15.5
```


inxi output

```
System:
  Host: home Kernel: 6.4.12-arch1-1 arch: x86_64 bits: 64 Desktop: sway
    v: 1.8.1 Distro: Arch Linux
Graphics:
  Device-1: AMD Navi 23 [Radeon RX 6600/6600 XT/6600M] driver: amdgpu v: kernel
  Display: wayland server: X.org v: 1.21.1.8 with: Xwayland v: 23.2.0
    compositor: sway v: 1.8.1 driver: gpu: amdgpu resolution: 1920x1080~75Hz
  Message: No known Wayland EGL/GBM data sources. API: EGL/GBM

```

**Comment by italovieira** [comment]
I'm having the same problem:

```
flameshot: error: Unable to capture screen
flameshot: error: Unable to capture screen
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```

```
Flameshot v12.1.0 (-)
Compiled with Qt 5.15.5
```


inxi output

```
System:
  Host: home Kernel: 6.4.12-arch1-1 arch: x86_64 bits: 64 Desktop: sway
    v: 1.8.1 Distro: Arch Linux
Graphics:
  Device-1: AMD Navi 23 [Radeon RX 6600/6600 XT/6600M] driver: amdgpu v: kernel
  Display: wayland server: X.org v: 1.21.1.8 with: Xwayland v: 23.2.0
    compositor: sway v: 1.8.1 driver: gpu: amdgpu resolution: 1920x1080~75Hz
  Message: No known Wayland EGL/GBM data sources. API: EGL/GBM

```

I have grim xdg-desktop-portal and xdg-desktop-portal-wlr installed as suggested in https://wiki.archlinux.org/index.php?title=Flameshot&oldid=778281#Flameshot_starts_with_an_error_on_Sway_/_wlroots.

**Comment by joaociocca** [comment]
this is really weird, I've been using flameshot without any trouble... and then, it stopped. When I use my meta+shift+s combo, a "portal" appears on the taskbar, then vanishes, and nothing happens.

![image](https://github.com/user-attachments/assets/6174301e-712e-4be0-a7ba-db761685b1ef)

when running `flameshot gui` from a terminal, I get a similar response:

```
2025-01-15 14:18:55  flameshot gui
QFont::fromString: Invalid description 'Fira Sans,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'FiraCode Nerd Font Mono,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'Fira Sans,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
QFont::fromString: Invalid description 'Fira Sans,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'
flameshot: error: Unable to capture screen
flameshot: error: Unable to capture screen
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
flameshot: info: Screenshot aborted.
```

specs:

```
System:
  Kernel: 6.12.9-zen1-1-zen arch: x86_64 bits: 64 compiler: gcc v: 14.2.1
    clocksource: tsc avail: acpi_pm
    parameters: BOOT_IMAGE=/@/boot/vmlinuz-linux-zen
    root=UUID=25d86c8c-ebff-4afc-ab94-381b01927087 rw rootflags=subvol=@
    quiet resume=UUID=67f41796-edab-4c43-8d65-0a5b35f8c01a loglevel=3 ibt=off
  Desktop: KDE Plasma v: 6.2.5 tk: Qt v: N/A info: frameworks v: 6.10.0
    wm: kwin_wayland vt: 1 dm: SDDM Distro: Garuda base: Arch Linux
Graphics:
  Device-1: Intel CoffeeLake-H GT2 [UHD Graphics 630] vendor: Dell
    driver: i915 v: kernel arch: Gen-9.5 process: Intel 14nm built: 2016-20
    ports: active: DP-5 off: eDP-1 empty: DP-2, DP-3, DP-4, DP-6, HDMI-A-2,
    HDMI-A-3 bus-ID: 0000:00:02.0 chip-ID: 8086:3e9b class-ID: 0300
  Device-2: NVIDIA TU106M [GeForce RTX 2060 Mobile] vendor: Dell
    driver: nvidia v: 565.77 alternate: nouveau,nvidia_drm non-free: 550/565.xx+
    status: current (as of 2025-01; EOL~2026-12-xx) arch: Turing code: TUxxx
    process: TSMC 12nm FF built: 2018-2022 ports: active: none off: HDMI-A-1
    empty: DP-1 bus-ID: 0000:01:00.0 chip-ID: 10de:1f11 class-ID: 0300
  Device-3: Microdia Integrated_Webcam_HD driver: uvcvideo type: USB
    rev: 2.0 speed: 480 Mb/s lanes: 1 mode: 2.0 bus-ID: 1-5:3 chip-ID: 0c45:671f
    class-ID: 0e02
  Display: wayland server: X.org v: 1.21.1.15 with: Xwayland v: 24.1.4
    compositor: kwin_wayland driver: X: loaded: modesetting,nvidia
    unloaded: nouveau alternate: fbdev,intel,nv,vesa dri: iris
    gpu: i915,nvidia,nvidia-nvswitch display-ID: 0
```
