### ISSUE TITLE
Weird behavior on Wayland with KDE

### ISSUE THREAD

**Issue by Gigas002** [flameshot-org/flameshot#3204]
### Flameshot Version

Flameshot v12.1.0 (3ededae5)

### Installation Type

User repository (AUR)

### Operating System type and version

Manjaro Linux

### Description

Flameshot's being very slow with screenshoting process and cropping screen to 1:4 of it's original size

### Screenshots or screen recordings

https://github.com/flameshot-org/flameshot/assets/24297712/6b9f5948-85b6-4e9e-adf6-4b81b9766c05

### System Information

```
System:
  Host: gigas-acer Kernel: 6.3.3-x64v3-xanmod1 arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.27.5 Distro: Manjaro Linux
Graphics:
  Device-1: NVIDIA GA106M [GeForce RTX 3060 Mobile / Max-Q] driver: nvidia
    v: 530.41.03
  Device-2: AMD Cezanne [Radeon Vega Series / Radeon Mobile Series]
    driver: amdgpu v: kernel
  Device-3: Quanta HD User Facing driver: uvcvideo type: USB
  Display: wayland server: X.org v: 1.21.1.8 with: Xwayland v: 23.1.1
    compositor: kwin_wayland driver: X: loaded: amdgpu,nvidia
    unloaded: modesetting,nouveau dri: radeonsi gpu: nvidia,amdgpu
    resolution: 1536x864
  API: OpenGL v: 4.6 Mesa 23.0.3 renderer: AMD Radeon Graphics (renoir LLVM
    15.0.7 DRM 3.52 6.3.3-x64v3-xanmod1)
 ```
