### ISSUE TITLE
Flameshot can not find screen on OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by binarypie** [flameshot-org/flameshot#3322]
### Flameshot Version

```
❱ flameshot --version
Flameshot v12.1.0 (-)
Compiled with Qt 5.15.10
```

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

openSUSE Tumbleweed 20230828 Kernel: 6.4.11-1-default arch: x86_64

### Description

I've spent a bunch of time trying to figure out what is going on here so as not to bother y'all but I'm still stuck.

### Steps to reproduce

1. Setup Gnome / Wayland from the official packages
2. Install Flameshot
3. Run `flameshot gui` 
4. Notice it does not launch as it can not find a monitor

### Screenshots or screen recordings

```
❱ flameshot gui
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland an
yway.
flameshot: error: Unable to capture screen
flameshot: error: Unable to capture screen
flameshot: info: Screenshot aborted
```

### System Information

<details>
<summary>The environment details</summary> 

```
❱ inxi --width 80 --system --graphics
System:
  Host: localhost.localdomain Kernel: 6.4.11-1-default arch: x86_64 bits: 64
    Desktop: GNOME v: 44.3 Distro: openSUSE Tumbleweed 20230828
Graphics:
  Device-1: AMD Navi 31 [Radeon RX 7900 XT/7900 XTX] driver: amdgpu v: kernel
  Device-2: Nanjing Magewell driver: N/A
  Device-3: NVIDIA TU102 [TITAN RTX] driver: nouveau v: kernel
  Device-4: Anker PowerConf C200
    driver: hid-generic,snd-usb-audio,usbhid,uvcvideo type: USB
  Display: wayland server: X.org v: 1.21.1.8 with: Xwayland v: 23.1.2
    compositor: gnome-shell driver: X: loaded: modesetting unloaded: fbdev,vesa
    dri: radeonsi,zink gpu: amdgpu resolution: 1: 3440x1440~175Hz
    2: 3440x1440~175Hz
  API: OpenGL v: 4.6 Mesa 23.1.5 renderer: AMD Radeon RX 7900 XTX (gfx1100
    LLVM 16.0.6 DRM 3.52 6.4.11-1-default)
```

</details>

<details>
<summary>The flameshot-gui content</summary>

```
❱ flameshot gui
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
flameshot: error: Unable to capture screen
flameshot: error: Unable to capture screen
flameshot: info: Screenshot aborted.
```

</details>

<details>
<summary>The dbus-monitor content</summary>

```
method call time=1693495467.380955 sender=:1.241 -> destination=org.freedesktop.DBus serial=4 path=/o
rg/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameO
wnerChanged',arg0='org.a11y.Bus',arg1=''"
method call time=1693495467.380991 sender=:1.241 -> destination=org.freedesktop.DBus serial=5 path=/o
rg/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameHasOwner
   string "org.a11y.Bus"
method call time=1693495467.381069 sender=:1.241 -> destination=org.freedesktop.DBus serial=6 path=/o
rg/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameO
wnerChanged',arg0='org.a11y.Bus'"
method call time=1693495467.381108 sender=:1.241 -> destination=org.freedesktop.DBus serial=7 path=/o
rg/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.a11y.Bus"
method call time=1693495467.381194 sender=:1.241 -> destination=org.a11y.Bus serial=8 path=/org/a11y/bus; interface=org.freedesktop.DBus.Properties; member=Get
   string "org.a11y.Status"
   string "ScreenReaderEnabled"
method call time=1693495467.381528 sender=:1.241 -> destination=org.a11y.Bus serial=9 path=/org/a11y/bus; interface=org.freedesktop.DBus.Properties; member=Get
   string "org.a11y.Status"
   string "IsEnabled"
```

</details>
