### ISSUE TITLE
Flameshot unable to capture screen when triggered through Gnome shortcut

### ISSUE THREAD

**Issue by kekonn** [flameshot-org/flameshot#3365]
### Flameshot Version

Flameshot v12.1.0 (-)
Compiled with Qt 5.15.10

### Installation Type

User repository (AUR)

### Operating System type and version

Arch with kernel 6.5.4-273-tkg-bore

### Description

When using a shortcut (Print screen) to run Flameshot I get "Unable to capture screen".

When I run the command from the shortcut in a terminal, it works.

Now both used to work fine before, but stopped working after my daily updates sometime this week. The normal Gnome screenshot program still works.

If you can tell me where I should look for further logs, please do, so I can upload them.

### Steps to reproduce

In Arch running Gnome:

1. Bind screenshot a region key to printscreen and set it to `/usr/bin/flameshot gui`
2. Use key to trigger flameshot
3. Get Unable to capture screen error

### Screenshots or screen recordings

![image](https://github.com/flameshot-org/flameshot/assets/149670/090781e9-9b60-4e76-9006-9dadfd4558e3)
(Shortcut settings)

### System Information

```
System:
  Host: tuxgamer Kernel: 6.5.4-273-tkg-bore arch: x86_64 bits: 64
    Desktop: GNOME v: 44.5 Distro: Arch Linux
Graphics:
  Device-1: AMD Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT]
    driver: amdgpu v: kernel
  Device-2: Logitech Brio 500 driver: hid-generic,usbhid,uvcvideo type: USB
  Device-3: Chicony USB2.0 FHD UVC WebCam driver: uvcvideo type: USB
  Display: wayland server: X.org v: 1.21.1.8 with: Xwayland v: 23.2.1
    compositor: gnome-shell driver: X: loaded: modesetting dri: radeonsi
    gpu: amdgpu resolution: 5120x1440~60Hz
  API: EGL v: 1.5 drivers: kms_swrast,radeonsi,swrast
    platforms: gbm,wayland,x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 23.2.1-arch1.2
    renderer: AMD Radeon RX 6700 XT (navi22 LLVM 16.0.6 DRM 3.54
    6.5.4-273-tkg-bore)
```
