### ISSUE TITLE
Segmentation fault when I try save a screenshot file

### ISSUE THREAD

**Issue by razykov** [flameshot-org/flameshot#3373]
### Flameshot Version

Flameshot v12.1.0 (-)
Compiled with Qt 5.15.10
linux: 6.5.5-arch1-1
arch: unknown

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...), User repository (AUR)

### Operating System type and version

Arch Linux 6.5.5-arch1-1 x86_64 GNU/Linux

### Description

When I try save a screenshot file the flameshot crashes. Running flameshot under gdb at the same steps:

```
Thread 1 "flameshot" received signal SIGSEGV, Segmentation fault.
QTextEngine::shapeTextWithHarfbuzzNG (this=this@entry=0x555555e5c5e0, si=..., string=string@entry=0x7fff23ff9028, itemLength=itemLength@entry=4096, 
    fontEngine=fontEngine@entry=0x5555558066e0, itemBoundaries=..., kerningEnabled=true, hasLetterSpacing=false)
    at ../../include/QtGui/5.15.11/QtGui/private/../../../../../src/gui/painting/qfixed_p.h:64
Downloading source file /usr/src/debug/qt5-base/qtbase/src/gui/../../include/QtGui/5.15.11/QtGui/private/../../../../../src/gui/painting/qfixed_p.h
64          Q_DECL_CONSTEXPR QFixed(int val, int) : val(val) {} // 2nd int is just a dummy for disambiguation                                                                                 
(gdb) bt
#0  QTextEngine::shapeTextWithHarfbuzzNG(QScriptItem const&, unsigned short const*, int, QFontEngine*, QVector<unsigned int> const&, bool, bool) const
    (this=this@entry=0x555555e5c5e0, si=..., string=string@entry=0x7fff23ff9028, itemLength=itemLength@entry=4096, fontEngine=fontEngine@entry=0x5555558066e0, itemBoundaries=..., kerningEnabled=true, hasLetterSpacing=false) at ../../include/QtGui/5.15.11/QtGui/private/../../../../../src/gui/painting/qfixed_p.h:64
#1  0x00007ffff701d07b in QTextEngine::shapeText(int) const (this=<optimized out>, item=<optimized out>) at text/qtextengine.cpp:1551
#2  0x00007ffff7035378 in QTextLine::layout_helper(int) (this=0x7fffffff9ef0, maxGlyphs=2147483647) at text/qtextlayout.cpp:1881
...
```
[Full stack-trace report](https://github.com/flameshot-org/flameshot/files/12874347/flameshot_pack_stack.txt)

### Steps to reproduce

1. run `flameshot`
2. Click on the flameshot tray icon
3. Select the screen region
4. Click `Save file`

### System Information

```
System:
  Host: pc Kernel: 6.5.5-arch1-1 arch: x86_64 bits: 64 Desktop: awesome
    v: 4.3 Distro: Arch Linux
Graphics:
  Device-1: Intel UHD Graphics 620 driver: i915 v: kernel
  Device-2: IMC Networks USB2.0 VGA UVC WebCam driver: uvcvideo type: USB
  Display: x11 server: X.org v: 1.21.1.8 driver: X: loaded: intel
    unloaded: modesetting dri: i965 gpu: i915 resolution: 1920x1080~60Hz
  API: EGL v: 1.5 drivers: iris,swrast platforms: x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel mesa v: 23.2.1-arch1.2
    renderer: Mesa Intel UHD Graphics 620 (KBL GT2)
```
