### ISSUE TITLE
Ctrl C does not work and low speed

### ISSUE THREAD

**Issue by Autumnlight02** [flameshot-org/flameshot#3417]
### Flameshot Version

Flameshot v12.1.0 ()
Compiled with Qt 5.15.5
linux: 6.2.9-300.fc38.x86_64
org.kde.Platform: 5.15-21.08

### Installation Type

Flatpak from Flathub

### Operating System type and version

Fedora Kionite 38 & Wayland

### Description

Ctrl C does not copy it onto my clipboard. I have to save the files to use it. Also when clicking the icon it takes like 8 seconds to take a screenshot. I am running Fedora Kionite 38 with wayland.

### Steps to reproduce

Open flameshot
take screenshot
select area
ctrl c (it closes it but clipboard is empty)

### System Information

(Taken inside of toolbox)

System:
Host: toolbox Kernel: 6.2.9-300.fc38.x86_64 arch: x86_64 bits: 64
Desktop: KDE Plasma v: ERR-101 Distro: Fedora release 38 (Thirty Eight)
Graphics:
Device-1: AMD Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT]
driver: amdgpu v: kernel
Device-2: [] driver: snd-usb-audio,uvcvideo type: USB
Display: wayland server: X.Org v: 22.1.9 compositor: kwin_wayland driver:
X: loaded: amdgpu unloaded: fbdev,modesetting,radeon,vesa dri: radeonsi
gpu: amdgpu resolution: 1: 1920x1080~75Hz 2: 2560x1440~75Hz
3: 1920x1080~60Hz 4: 1920x1080~75Hz
API: EGL Message: EGL data requires eglinfo. Check --recommends.

**Comment by mmahmoudian** [comment]
Thanks for the bug report, but would you please clarify if Ctrl+c does not work or cppying in general does not work (e.g clicking on copy button)?

**Comment by Autumnlight02** [comment]
@mmahmoudian Clicking on the copy icon when it opens up fails as well

**Comment by Autumnlight02** [comment]
Would you like a vidoe @mmahmoudian

**Comment by mmahmoudian** [comment]
No, this sounds like a duplicate of wayland portal copy issue. We need to work on that

**Comment by tjb0607** [comment]
Copying doesn't seem to work under X, either. I'm running under i3-wm 4.23 on Arch. I tried with the binary from the arch repos (extra/flameshot 12.1.0-3), compiling from source through aur/flameshot-git (3d21e496), and the Flatpak, and none of those work.

```
Flameshot v12.1.0 (3d21e496)
Compiled with Qt 5.15.12
linux: 6.6.10-arch1-1
```

```
System:
  Host: tjbdesktop Kernel: 6.6.10-arch1-1 arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.27.10 Distro: Arch Linux
Graphics:
  Device-1: Intel Raptor Lake-S GT1 [UHD Graphics 770] driver: i915 v: kernel
  Device-2: AMD Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT]
    driver: amdgpu v: kernel
  Device-3: Blackmagic Design Intensity Pro 4K driver: blackmagic-io
    v: 12.7a4
  Device-4: Logitech C920 PRO HD Webcam driver: snd-usb-audio,uvcvideo
    type: USB
  Device-5: Logitech C922 Pro Stream Webcam driver: snd-usb-audio,uvcvideo
    type: USB
  Display: server: X.Org v: 21.1.10 with: Xwayland v: 23.2.3 driver: X:
    loaded: amdgpu dri: radeonsi gpu: amdgpu resolution: 1: 2560x1440~165Hz
    2: 2560x1440~60Hz 3: 1080x1920~60Hz 4: 1920x1080~75Hz
  API: EGL v: 1.5 drivers: iris,radeonsi,swrast
    platforms: x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 23.3.2-arch1.2
    renderer: AMD Radeon RX 6700 XT (radeonsi navi22 LLVM 16.0.6 DRM 3.54
    6.6.10-arch1-1)
  API: Vulkan v: 1.3.274 drivers: radv surfaces: xcb,xlib
```
