### ISSUE TITLE
screenshots are discolored [Wayland, KDE]

### ISSUE THREAD

**Issue by lastendcondctor** [flameshot-org/flameshot#3429]
### Flameshot Version

Flameshot v12.1.0 (3d21e496)
Compiled with Qt 5.15.11

### Installation Type

User repository (AUR)

### Operating System type and version

Arch Linux

### Description

noticed a trend of flameshot on wayland not properly using the same colors, same issue as described [here](https://github.com/flameshot-org/flameshot/issues/3196). can confirm it definitely wasnt a problem on x11. originally considered it an issue with how the opacity outside area selection layer was applied but there's no difference in color whether its at 0% or 100%.

### Steps to reproduce

1. run any screenshot command
2. select region in the blank space of a chat app (as example)
3. paste said image in the chat of same chat app
4. notice difference in color between image and background color of chat app when there shouldn't be any

### Screenshots or screen recordings

<details>

<summary>video preview</summary>

https://github.com/flameshot-org/flameshot/assets/80832006/606529f4-16c7-428f-99f6-31a575ce49af

</details>

<details>

<summary>image taken from video preview</summary>

![image](https://github.com/flameshot-org/flameshot/assets/80832006/a1d9ef8a-60cd-46c9-ab20-973ec8c1264f)

</details>

<details>

<summary>image taken in x11 with the same app theme</summary>

![image](https://github.com/flameshot-org/flameshot/assets/80832006/69ed856b-fe41-4e84-a222-1d075cf4857f)

</details>

<details>

<summary>images merged for quick comparison</summary>

![image](https://github.com/flameshot-org/flameshot/assets/80832006/327f7ec2-b37b-4683-962a-3ebd3eb831bb)

</details>

### System Information

<details>

<summary>inxi</summary>

```
System:
    Host: pudding Kernel: 6.6.4-arch1-1 arch: x86_64 bits: 64 Desktop: KDE Plasma
    v: 5.90.0 Distro: Arch Linux
Graphics:
  Device-1: Intel DG2 [Arc A770] driver: i915 v: kernel
  Display: wayland server: X.org v: 1.21.1.9 with: Xwayland v: 23.2.2
    compositor: kwin_wayland driver: X: loaded: modesetting dri: iris gpu: i915
    resolution: 1: 1920x1080~165Hz 2: 1920x1080~144Hz
  API: EGL v: 1.5 drivers: iris,swrast
    platforms: wayland,x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel v: N/A renderer: Mesa Intel
    Arc A770 Graphics (DG2)
```

</details>

<details>

<summary>display configuration</summary>

![image](https://github.com/flameshot-org/flameshot/assets/80832006/8e519d67-6cc5-40b7-a655-036f6a57b83e)

</details>
