### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by Patrick-Poitras** [flameshot-org/flameshot#3454]
### Flameshot Version

```
patrick@localhost:~> flameshot --version
Flameshot v12.1.0 (-)
Compiled with Qt 5.15.11
```

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

OpenSUSE TW. 

### Description

Triggering flameshot after taking a screenshot, by either using a hotkey bound to Win+Shift+S (in i3 config):

```
bindsym $mod+Shift+s exec flameshot gui
```

Or by clicking on the icon in the notification bar. 

The result is that the window shows up with the click-drag selection window. The violet/magenta circles with icons in them appear, but without the icons. 

Let me know of any troubleshooting I can do to help narrowing it down.

Edit: Some additional notes:
- I have a fairly minimal system, so the issue might be with some runtime dependency that is assumed to be present on all systems
- It used to work before, but it broke a few months ago.
- The last update of this package on OpenSUSE's repos is 8 months ago

### Steps to reproduce

1. Run flameshot GUI.
2. Click-drag
3. The purple bits appear without icons :(

### Screenshots or screen recordings

![Peek 2023-12-29 14-43](https://github.com/flameshot-org/flameshot/assets/42386710/ce1bddd8-8071-4762-85fd-b0ab9f33fb46)

### System Information

```
patrick@localhost:~> uname -a
Linux localhost.localdomain 6.6.7-1-default #1 SMP PREEMPT_DYNAMIC Thu Dec 14 17:36:48 UTC 2023 (6869d09) x86_64 x86_64 x86_64 GNU/Linux
```
OpenSUSE TW. i3/X11
````
patrick@localhost:~> inxi --width 80 --system --graphics
System:
  Host: localhost.localdomain Kernel: 6.6.7-1-default arch: x86_64 bits: 64
    Desktop: i3 v: 4.23 Distro: openSUSE Tumbleweed 20231226
Graphics:
  Device-1: AMD Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT]
    driver: amdgpu v: kernel
  Device-2: AMD Cezanne [Radeon Vega Series / Radeon Mobile Series]
    driver: amdgpu v: kernel
  Display: x11 server: X.org v: 1.21.1.9 driver: X: loaded: modesetting
    unloaded: fbdev,vesa dri: radeonsi gpu: amdgpu resolution: 1920x1080~300Hz
  API: OpenGL v: 4.6 vendor: amd mesa v: 23.2.1 renderer: AMD Radeon
    Graphics (renoir LLVM 17.0.6 DRM 3.54 6.6.7-1-default)
  API: Vulkan v: 1.3.268 drivers: radv surfaces: xcb,xlib
```
