### ISSUE TITLE
Flameshot appears behind fullscreen windows on Sway

### ISSUE THREAD

**Issue by Octelly** [flameshot-org/flameshot#3470]
### Flameshot Version

Flameshot v12.1.0 (-)
Compiled with Qt 5.15.10

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Arch

### Description

Flameshot seems to not be using the layer shell protocol thing (I'm not super faimiliar wit this), which seems to cause it appearing behind fullscreen windows. This does not happen with apps that do support the protocol, such as [Sway Notification Center](https://github.com/ErikReider/SwayNotificationCenter).

I use this command to check current layer shell surfaces: ``swaymsg -r -t get_outputs | jq '.[0].layer_shell_surfaces | .[] | .namespace'`` (taken from [SwayFX readme](https://github.com/WillPower3309/swayfx/blob/f0ecffe593574593ec99c104fa12e4bfd593b0f2/README.md?plain=1#L47))

### Steps to reproduce

1. Have a fullscreen app open
2. Use shortcut to open Flameshot (I usually use ``flameshot gui -c -p "$HOME/Pictures/$(date +%s).png"``)
3. Flameshot appears behind fullscreen window

### System Information

**Arch Linux (rolling)**

**Output settings**
```
output HDMI-A-1 resolution 1920x1080@60Hz position 0,320
output DP-3 resolution 1920x1080@60Hz position 1920,0
```

**inxi**
```
System:
  Host: xia-pc Kernel: 6.6.10-zen1-1-zen arch: x86_64 bits: 64 Desktop: sway
    v: 0.3.2-f0ecffe5 Distro: Arch Linux
Graphics:
  Device-1: AMD Navi 14 [Radeon RX 5500/5500M / Pro 5500M] driver: amdgpu
    v: kernel
  Device-2: Microdia Webcam Vitade AF driver: snd-usb-audio,uvcvideo
    type: USB
  Display: wayland server: X.org v: 1.21.1.10 with: Xwayland v: 23.2.3
    compositor: sway v: 0.3.2-f0ecffe5 driver: X: loaded: amdgpu
    unloaded: modesetting dri: radeonsi gpu: amdgpu resolution:
    1: 1920x1080~60Hz 2: 1920x1080~60Hz
  API: EGL v: 1.5 drivers: radeonsi,swrast
    platforms: wayland,x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 23.3.2-arch1.2
    renderer: AMD Radeon RX 5500 XT (radeonsi navi14 LLVM 16.0.6 DRM 3.54
    6.6.10-zen1-1-zen)
```

I use SwayFX, which is a fork of Sway. It adds some extra features.
