### ISSUE TITLE
Screenshots aren't copied to the clipboard

### ISSUE THREAD

**Issue by OnkelTem** [flameshot-org/flameshot#3479]
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.12.8

### Installation Type

AppImage

### Operating System type and version

Linux Kubuntu 22.04

### Description

I can't copy screenshot to the clipboard. When I click this button, flameshot silently exists.
I activate Flameshot via Print Screen, which is assigned to `flameshot gui --delay 2500`

Currently the only option left working is saving screenshot to file :(

### Steps to reproduce

1. Import KDE shortcuts
2. Assign Print Screen to "Take screenshot with delay" which is the second option with command `flameshot gui --delay 2500`
3. Press Print Screen, make selection
4. Press copy. 

### System Information

```
$ inxi --width 80 --system --graphics
System:
  Host: fractal Kernel: 6.5.0-14-generic x86_64 bits: 64
    Desktop: KDE Plasma 5.24.7 Distro: Ubuntu 22.04.3 LTS (Jammy Jellyfish)
Graphics:
  Device-1: NVIDIA GA104 [GeForce RTX 3060 Ti Lite Hash Rate] driver: nvidia
    v: 525.147.05
  Device-2: Logitech BRIO Ultra HD Webcam type: USB
    driver: hid-generic,snd-usb-audio,usbhid,uvcvideo
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: nvidia
    unloaded: fbdev,modesetting,nouveau,vesa gpu: nvidia resolution:
    1: 2560x1440~144Hz 2: 1920x1080~60Hz 3: 1920x1080~60Hz
  OpenGL: renderer: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
    v: 4.6.0 NVIDIA 525.147.05
```

**Comment by mmahmoudian** [comment]
Flameshot definitely works flawlessly on X11.

Based on your text I think you are not experienced enough with Linux. So here is what you should do:
1. If you are using AppImage, you cannot use `flameshot`. You have to run that Flameshot AppImage (this is how AppImage works). We have clearly explained it in our documentation ( https://flameshot.org/docs/installation/installation-linux/#appimage )
2. remove the `--delay 500`, that is not needed, it will just add half a second delay
3. If the above didn't fix the issue, open a terminal and run `flameshot` (in your case `./ Flameshot-12.1.0.x86_64.AppImage`), then open another terminal and run `flameshot gui` (in your case `./ Flameshot-12.1.0.x86_64.AppImage gui`). Then try to copy. It should work

**Comment by OnkelTem** [comment]
No, unfortunately it doesn't work anyway. 

1. I used the `flameshot` command because I created a symlink.
2. Delay isn't in charge, the problem with AppImage is that it seem to be exist before putting image to the clipboard.
3. When I run `flameshot gui` manually, it works.

**Comment by dxomg** [comment]
I also have this kind of problem here's a recording of how I did it, I'm currently using Debian 12 with Xfce as my DE, It does appear to put some type of image on the clipboard but it is an invalid image, If the screenshot is a lower resolution or its just a window it does appear to work properly.


```
dxomg@dxomg:~$ inxi --width 80 --system --graphics
System:
  Host: dxomg Kernel: 6.1.0-17-amd64 arch: x86_64 bits: 64 Desktop: Xfce
    v: 4.18.1 Distro: Debian GNU/Linux 12 (bookworm)
Graphics:
  Device-1: Intel Haswell-ULT Integrated Graphics driver: i915 v: kernel
  Device-2: NVIDIA GK208M [GeForce GT 730M] driver: nvidia v: 470.223.02
  Device-3: IMC Networks Lenovo EasyCamera type: USB driver: uvcvideo
  Display: x11 server: X.Org v: 1.21.1.7 with: Xwayland v: 22.1.9 driver: X:
    loaded: modesetting,nvidia unloaded: fbdev,nouveau,vesa dri: crocus gpu: i915
    resolution: 1920x1080~60Hz
  API: OpenGL v: 4.6 Mesa 22.3.6 renderer: Mesa Intel HD Graphics 4400 (HSW
    GT2
```


https://github.com/flameshot-org/flameshot/assets/101947415/c868ce0a-0e78-4cb6-be22-ad21b4e1e248
