### ISSUE TITLE
Magnifier can go off-screen if whole monitor setup isn't perfectly rectangular

### ISSUE THREAD

**Issue by Orthestral** [flameshot-org/flameshot#3568]
### Flameshot Version

Flameshot v12.1.0 (-)
Compiled with Qt 5.15.4

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Linux 6.6.25

### Description

The magnifier uses the entire monitor setup as a bounding box rather than just the usable screen space, meaning it can go off-screen if it's moved into empty space, rather than switching sides to stay visible. The buttons don't have this issue.

### Steps to reproduce

1. Set up multiple monitors where the entire area isn't rectangular, such as by offsetting the monitor. Make sure the empty space is to the bottom or right of any screen space
2. Take a screenshot with the magnifier on
3. Move the magnifier off-screen where the empty space is

### Screenshots or screen recordings

Black section is off-screen
![image](https://github.com/flameshot-org/flameshot/assets/76718984/9caca75e-6508-462a-9846-ba77dc676c76)

### System Information

```
System:
  Host: xxxxxxxx Kernel: 6.6.25_1 arch: x86_64 bits: 64
  Desktop: GNOME v: 45.5 Distro: Void Linux
Graphics:
  Device-1: NVIDIA TU104 [GeForce RTX 2070 SUPER] driver: nvidia v: 550.67
  Display: x11 server: X.Org v: 21.1.13 with: Xwayland v: 23.2.4 driver: X:
    loaded: nvidia gpu: nvidia,nvidia-nvswitch resolution: 1: 1920x1080~144Hz
    2: 1920x1080~144Hz 3: 1080x1920~144Hz
  API: OpenGL v: 4.6.0 vendor: nvidia v: 550.67 renderer: NVIDIA GeForce RTX
    2070 SUPER/PCIe/SSE2
  API: Vulkan v: 1.3.268 drivers: nvidia surfaces: xcb,xlib
  API: EGL Message: EGL data requires eglinfo. Check --recommends.
```
![image](https://github.com/flameshot-org/flameshot/assets/76718984/db42e282-d5cd-4460-bb6a-67eb8c82bce2)
